server:
  port: 8082

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  output:
    ansi:
      enabled: always
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/shophandmade
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

